/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import banco.Banco;
import dados.Fornecedor;
import dados.SessaoUsuario;
/**
 *
 * @author User
 */
public class TelaCadastrarFornecedor extends javax.swing.JFrame {
   private Fornecedor fornecedor;
   private Banco banco;
   private String nome;
   private String cnpj;
   private String telefone;
   private String email;
   private String cep;
   private SessaoUsuario i;
   private String bairro;
   private String rua;
   private String numero;
    public TelaCadastrarFornecedor() {
        initComponents();
        banco = new Banco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoTelefone = new javax.swing.JTextField();
        CampoCep = new javax.swing.JTextField();
        CampoBairro = new javax.swing.JTextField();
        CampoRua = new javax.swing.JTextField();
        CampoNumero = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoNome = new javax.swing.JTextField();
        CampoCnpj = new javax.swing.JTextField();
        BotaoConcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        CampoTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoTelefoneKeyPressed(evt);
            }
        });
        getContentPane().add(CampoTelefone);
        CampoTelefone.setBounds(200, 500, 330, 50);

        CampoCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoCepKeyPressed(evt);
            }
        });
        getContentPane().add(CampoCep);
        CampoCep.setBounds(890, 250, 360, 50);

        CampoBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoBairroKeyPressed(evt);
            }
        });
        getContentPane().add(CampoBairro);
        CampoBairro.setBounds(890, 370, 360, 50);

        CampoRua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoRuaKeyPressed(evt);
            }
        });
        getContentPane().add(CampoRua);
        CampoRua.setBounds(890, 490, 360, 50);

        CampoNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroActionPerformed(evt);
            }
        });
        CampoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoNumeroKeyPressed(evt);
            }
        });
        getContentPane().add(CampoNumero);
        CampoNumero.setBounds(890, 610, 160, 50);

        CampoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoEmailKeyPressed(evt);
            }
        });
        getContentPane().add(CampoEmail);
        CampoEmail.setBounds(200, 620, 360, 50);

        CampoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });
        CampoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoNomeKeyPressed(evt);
            }
        });
        getContentPane().add(CampoNome);
        CampoNome.setBounds(200, 250, 350, 50);

        CampoCnpj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoCnpjKeyPressed(evt);
            }
        });
        getContentPane().add(CampoCnpj);
        CampoCnpj.setBounds(200, 380, 340, 50);

        BotaoConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/concluir-removebg-preview.png"))); // NOI18N
        BotaoConcluir.setText("Concluir");
        BotaoConcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoConcluir);
        BotaoConcluir.setBounds(1140, 670, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/cadastrarfornecedor1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, -40, 1420, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroActionPerformed

    private void BotaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConcluirActionPerformed
        nome = CampoNome.getText();
        cnpj = CampoCnpj.getText();
        telefone = CampoTelefone.getText();
        email = CampoEmail.getText();
        cep = CampoCep.getText();
        bairro = CampoBairro.getText();
        rua = CampoRua.getText();
        numero = CampoNumero.getText();
        i = new SessaoUsuario();
        System.out.println("id = "+i.getId());
        fornecedor = new Fornecedor(nome,cnpj,telefone,email,cep,bairro,rua,numero);
        banco.registrardadosFornecedor(fornecedor);
        CampoNome.setText("");
        CampoCnpj.setText("");
        CampoTelefone.setText("");
        CampoEmail.setText("");
        CampoCep.setText("");
        CampoBairro.setText("");
        CampoRua.setText("");
        CampoNumero.setText("");
    }//GEN-LAST:event_BotaoConcluirActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void CampoNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNomeKeyPressed
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoCnpj.requestFocus(); 
            }
    }//GEN-LAST:event_CampoNomeKeyPressed

    private void CampoCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCnpjKeyPressed
           if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoTelefone.requestFocus(); 
            }
    }//GEN-LAST:event_CampoCnpjKeyPressed

    private void CampoTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoTelefoneKeyPressed
             if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoEmail.requestFocus(); 
            }
    }//GEN-LAST:event_CampoTelefoneKeyPressed

    private void CampoEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoEmailKeyPressed
              if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoCep.requestFocus(); 
            }
    }//GEN-LAST:event_CampoEmailKeyPressed

    private void CampoCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCepKeyPressed
              if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoBairro.requestFocus(); 
            }
    }//GEN-LAST:event_CampoCepKeyPressed

    private void CampoBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBairroKeyPressed
             if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoRua.requestFocus(); 
            }
    }//GEN-LAST:event_CampoBairroKeyPressed

    private void CampoRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoRuaKeyPressed
             if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                CampoNumero.requestFocus(); 
            }
    }//GEN-LAST:event_CampoRuaKeyPressed

    private void CampoNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNumeroKeyPressed
                     if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                BotaoConcluir.requestFocus(); 
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                BotaoConcluir.doClick();
            }  
    }//GEN-LAST:event_CampoNumeroKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConcluir;
    private javax.swing.JTextField CampoBairro;
    private javax.swing.JTextField CampoCep;
    private javax.swing.JTextField CampoCnpj;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNumero;
    private javax.swing.JTextField CampoRua;
    private javax.swing.JTextField CampoTelefone;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
