/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import banco.Banco;
import dados.CriarConta;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class TelaCriarConta extends javax.swing.JFrame {
    
    private String email;
    private String senha;
    private String repetirSenha;
    private Banco banco;
    private CriarConta criarConta;
    public TelaCriarConta() {
        initComponents();
       banco = new Banco();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoRepetirSenha = new javax.swing.JPasswordField();
        campoEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        campoRepetirSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoRepetirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRepetirSenhaActionPerformed(evt);
            }
        });
        campoRepetirSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoRepetirSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(campoRepetirSenha);
        campoRepetirSenha.setBounds(520, 410, 260, 60);

        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        campoEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoEmailKeyPressed(evt);
            }
        });
        jPanel1.add(campoEmail);
        campoEmail.setBounds(520, 240, 260, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/Simple_Lined_White_Login_Page_Wireframe_Website_UI_Prototype-removebg-preview.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 520, 170, 50);

        campoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        campoSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(campoSenha);
        campoSenha.setBounds(520, 320, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/criarconta00.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1450, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        email = campoEmail.getText();
        senha = new String (campoSenha.getPassword());
        if(email != null && !email.trim().isEmpty() && senha != null && !senha.trim().isEmpty())
        {
            if(email.contains("@"))
            {
            repetirSenha = new String (campoRepetirSenha.getPassword());
            if(senha.equals(repetirSenha))
            {
                criarConta = new CriarConta(email,senha);
                banco.registrarNoBanco(criarConta);
                campoEmail.setText("");
                campoSenha.setText("");
                campoRepetirSenha.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "As senhas não coincidem. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
                System.out.println("senha incorreta");
            }
            }else
            {
            JOptionPane.showMessageDialog(this, "Campo email sem o caractere @.", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        }else
        {
            JOptionPane.showMessageDialog(this, "Campo email ou senha não preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed

    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoRepetirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRepetirSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRepetirSenhaActionPerformed

    private void campoEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEmailKeyPressed
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoSenha.requestFocus(); 
            }
    }//GEN-LAST:event_campoEmailKeyPressed

    private void campoSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSenhaKeyPressed
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                campoRepetirSenha.requestFocus(); 
            }
    }//GEN-LAST:event_campoSenhaKeyPressed

    private void campoRepetirSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRepetirSenhaKeyPressed
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.requestFocus(); 
            }
   
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jButton1.doClick();
            }  
    }//GEN-LAST:event_campoRepetirSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoEmail;
    private javax.swing.JPasswordField campoRepetirSenha;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
