/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dados.ProdutosCardapio;
import banco.Banco;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
/**
 *
 * @author User
 */
public class TelaExibirCardapio extends javax.swing.JFrame {
private ProdutosCardapio produto;
private Banco banco;
    /**
     * Creates new form TelaExibirCardapio
     */
    public TelaExibirCardapio() {
        initComponents();
         banco = new Banco();
        setTitle("Cardápio");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1366, 768);
        setLayout(null);

        JPanel painelProdutos = new JPanel();
        painelProdutos.setLayout(null);
        painelProdutos.setPreferredSize(new Dimension(1366, 768)); 

        List<ProdutosCardapio> produtos = banco.obterProdutos(); 
        int num = produtos.size();
        int x = 10; 
        int y = 10; 
        int largura = 250;
        int altura = 400;
        int margem = 10; 

        JLabel[] labelImagem = new JLabel[num];

        for (int i = 0; i < num; i++) { 
            ProdutosCardapio produto = produtos.get(i);
            JPanel painelProduto = new JPanel();
            painelProduto.setLayout(null);
            painelProduto.setBounds(0, 0, largura, altura); 
            painelProduto.setBackground(Color.white);

            if (produto.getCaminho() != null && !produto.getCaminho().isEmpty()) {
                try {
                    labelImagem[i] = new JLabel(new ImageIcon(produto.getCaminho()));
                } catch (Exception e) {
                    labelImagem[i] = new JLabel(new ImageIcon(getClass().getResource("iconfoto.png")));
                }
            } else {
                labelImagem[i] = new JLabel(new ImageIcon(getClass().getResource("iconfoto.png")));
            }

            labelImagem[i].setBounds(0, 0, largura, 250); 
            painelProduto.add(labelImagem[i]);

           
            JLabel labelNome = new JLabel(produto.getNome(), SwingConstants.CENTER);
            labelNome.setFont(new Font("Arial", Font.BOLD, 14));
            labelNome.setBounds(0, 260, largura, 30); 
            painelProduto.add(labelNome);

            
            JLabel labelPreco = new JLabel(String.format("R$ %.2f", Double.parseDouble(produto.getPreco())), SwingConstants.CENTER);
            labelPreco.setFont(new Font("Arial", Font.PLAIN, 12));
            labelPreco.setBounds(0, 300, largura, 20); 
            painelProduto.add(labelPreco);

            
           
            painelProdutos.add(painelProduto);
            painelProduto.setBounds(x, y, largura, altura);
            painelProdutos.setBackground(Color.white);

            
            x += largura + margem;
            if ((i + 1) % 5 == 0) {
                x = 10; 
                y += altura + margem; 
            }
        }

        JScrollPane scrollPane = new JScrollPane(painelProdutos);
        scrollPane.setBounds(0, 0, 1366, 768);
        add(scrollPane);
    }  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
