/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dados.Fornecedor;
import dados.FornecedorAtualizado;
import banco.Banco;
/**
 *
 * @author User
 */
public class TelaEditarFornecedor extends javax.swing.JFrame {
    private FornecedorAtualizado fornecedorAt;
    private Fornecedor fornecedor;
    private String nomeFornecedor;
    private Banco banco;
    private String nome;
    private String nomeAntigo;
    public TelaEditarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoCnpj = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoCep = new javax.swing.JTextField();
        campoRua = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoNomeFornecedor = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        campoCnpj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoCnpj);
        campoCnpj.setBounds(230, 410, 310, 40);

        campoTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoTelefone);
        campoTelefone.setBounds(230, 520, 310, 40);

        campoNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoNumero);
        campoNumero.setBounds(850, 630, 230, 40);

        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoEmail);
        campoEmail.setBounds(230, 630, 310, 40);

        campoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoNome);
        campoNome.setBounds(230, 300, 310, 40);

        campoCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoCep);
        campoCep.setBounds(850, 300, 280, 40);

        campoRua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoRua);
        campoRua.setBounds(850, 520, 300, 40);

        campoBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(campoBairro);
        campoBairro.setBounds(850, 400, 310, 40);

        campoNomeFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(campoNomeFornecedor);
        campoNomeFornecedor.setBounds(470, 160, 140, 30);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/buscar-removebg-preview.png"))); // NOI18N
        jToggleButton1.setText("buscar");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(660, 160, 110, 30);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/concluir-removebg-preview.png"))); // NOI18N
        jToggleButton2.setText("Concluir");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(1130, 670, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/Editar fornecedor.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1460, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeFornecedorActionPerformed
      
    }//GEN-LAST:event_campoNomeFornecedorActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        fornecedor = new Fornecedor();
        banco = new Banco();
        nomeFornecedor = campoNomeFornecedor.getText();
        
        fornecedor = banco.buscarFornecedor(nomeFornecedor);
        
        campoNome.setText(fornecedor.getNome());
        nomeAntigo = campoNome.getText();
        campoCnpj.setText(fornecedor.getCnpj());
        campoTelefone.setText(fornecedor.getTelefone());
        campoEmail.setText(fornecedor.getEmail());
        campoCep.setText(fornecedor.getCep());
        campoBairro.setText(fornecedor.getBairro());
        campoRua.setText(fornecedor.getRua());
        campoNumero.setText(fornecedor.getNumero());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        fornecedorAt = new FornecedorAtualizado();
        fornecedorAt.setNome(campoNome.getText());
        fornecedorAt.setCnpj(campoCnpj.getText());
        fornecedorAt.setTelefone(campoTelefone.getText());
        fornecedorAt.setEmail(campoEmail.getText());
        fornecedorAt.setCep(campoCep.getText());
        fornecedorAt.setBairro(campoBairro.getText());
        fornecedorAt.setRua(campoRua.getText());
        fornecedorAt.setNumero(campoNumero.getText());
        banco.editarFornecedor(fornecedorAt,nomeAntigo);
          
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCnpj;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeFornecedor;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRua;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
